package com.inventory.backend.inventory;

public enum InventoryRemovalReason {
    SALE,
    PURCHASE,
    INITIAL_INVENTORY,
    CUSTOMER_RETURN,
    SUPPLIER_REPLACEMENT,
    RESTOCK,
    TRANSFER_IN,
    AMAZON_RETURN,
    WAREHOUSE_CORRECTION,
    DAMAGED,
    LOST,
    EXPIRED,
    EXPIRED_INVENTORY,
    UNSELLABLE,
    DESTROYED,
    INVENTORY_AUDIT,
    PHYSICAL_COUNT_CORRECTION,
    WAREHOUSE_RESET,
    SYSTEM_CORRECTION,
    WAREHOUSE_CLEANUP,
    INCORRECT_COUNT,
    OTHER
}
